apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fe4pw3621-python 
  janus-idp.io/tekton: fe4pw3621-python
  backstage.io/kubernetes-id: fe4pw3621-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fe4pw3621-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml